name: Баг сервера
description: A problem in the Ability Draft game mode

labels: ["server-bug"]

body:
  - type: textarea
    id: desc
    attributes:
      label: Описание
      placeholder: В чем заключается проблема?
    validations:
      required: true

  - type: input
    id: match-id
    attributes:
      label: Example Match ID (and possibly Timestamp)
      placeholder: ex. 6575941888 - 03:22
    validations:
      required: true
